### ISSUE TITLE
Change: -cfnext doesn't return the latest contests

### ISSUE THREAD

**Issue by rtwksai** [DaKeiser/contest-bot#3]
`-cfnext` command doesn't return the latest commands.
Rather it returns by reversing the list given by the API and then , which is incorrect in implementation.

**Solution:**
Use `relativeTimeSeconds` to sort the contests, and then send the first few contests accordingly.

**Comment by preeti13456** [comment]
What's relativeTimeSeconds here? Does it is a method or an approach?

**Comment by rtwksai** [comment]
Hi @preeti13456, Sorry I didn't get notified about this. But yes, if you look at [Codeforces API](https://codeforces.com/api/contest.list), you will find that the object has a key `relativeTimeSeconds`. That is the variable in context
